---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: 'brianhartsock.mdadm'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'brianhartsock.mdadm'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies.
        run: |
          pip3 install -r requirements.txt
          pip3 install ansible-lint

      - name: Ansible Lint
        run: ansible-lint

      - name: YAML Lint
        run: yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'brianhartsock.mdadm'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies.
        run: pip3 install -r requirements.txt

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
